import {
  SiteSettings,
  VisionMissions,
  NewsArticle,
  DivisionMember,
  MemberDirectory,
  StudentProject,
  GalleryItem,
} from "@/types";

/**
 * Data fallback cadangan ketika tabel Supabase offline atau belum terisi.
 * Menjamin tampilan website tetap terisi data valid tanpa jeda atau error.
 */
export const fallbackSiteSettings = {
  current_period: "2026",
  email: "hmps-ti@stmik-widya-utama.ac.id",
  whatsapp: "+62 812-3456-7890",
  address: "Gedung Kampus STMIK Widya Utama, Jl. Sunan Kalijaga No.26, Purwokerto, Jawa Tengah",
  map_embed_url:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3956.402517855325!2d109.24712497499999!3d-7.420601992589712!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e655e783424d86b%3A0xb3556d787019f182!2sSTMIK%20Widya%20Utama!5e0!3m2!1sid!2sid!4v1700000000000!5m2!1sid!2sid",
};

export const fallbackVisionMissions = {
  vision:
    "Menjadi Himpunan Mahasiswa Teknik Informatika yang Unggul, Inovatif, dan Berkarakter dalam Penguasaan Teknologi Digital serta Berkontribusi Aktif Bagi Kemajuan Kampus dan Masyarakat.",
  missions: [
    {
      number: "01",
      title: "Meningkatkan Kualitas Akademik & Kompetensi Teknologi",
      desc: "Menyelenggarakan pelatihan rutin, riset terapan, dan sertifikasi keahlian dalam bidang pemrograman, AI, cloud computing, dan rekayasa perangkat lunak.",
      indicator: "120+ Mahasiswa Bersertifikasi Per Periode",
    },
    {
      number: "02",
      title: "Membangun Ekosistem Karya & Inovasi Mahasiswa",
      desc: "Wadah pendampingan dan publikasi produk software inovatif buatan mahasiswa prodi Teknik Informatika agar siap bersaing secara nasional.",
      indicator: "40+ Karya Terpublikasi di Showcase",
    },
    {
      number: "03",
      title: "Mempererat Keakraban & Kaderisasi Berkelanjutan",
      desc: "Mengembangkan potensi kepemimpinan, karakter etis, dan kebersamaan seluruh mahasiswa TI melalui program upgraded kaderisasi yang humanis.",
      indicator: "100% Partisipasi Mahasiswa Baru",
    },
    {
      number: "04",
      title: "Meningkatkan Kemitraan Eksternal & Pengabdian",
      desc: "Jejaring kolaborasi dengan industri teknologi, asosiasi mahasiswa TI nasional, dan pengabdian masyarakat berbasis edukasi teknologi digital.",
      indicator: "10+ Kemitraan Industri & Instansi",
    },
    {
      number: "05",
      title: "Tata Kelola Organisasi yang Transparan & Adaptif",
      desc: "Menjalankan roda organisasi HMPSTI SWU berbasis teknologi digital, akuntabilitas keuangan, serta komunikasi publik yang responsif.",
      indicator: "Laporan Keuangan & Proker Terbuka",
    },
  ],
};

export const fallbackNews = [
  {
    id: "news-1",
    slug: "pelatihan-framework-modern-nextjs-15",
    title: "Pelatihan Framework Modern Next.js 15 & Supabase untuk Mahasiswa STMIK Widya Utama",
    category: "Workshop",
    is_event: false,
    author_name: "Divisi LPT",
    created_at: new Date().toISOString(),
    event_date: null,
    reading_time: "4 min read",
    likes_count: 0,
    excerpt: "Divisi Literasi & Pengembangan Teknologi HMPSTI SWU sukses menggelar workshop intensif pengembangan web modern dengan integrasi database Supabase.",
    content: "Divisi Literasi & Pengembangan Teknologi (LPT) HMPSTI STMIK Widya Utama sukses menggelar kegiatan workshop teknologi terdepan bertajuk mastering Next.js 15 App Router & Edge Database Supabase. Acara diselenggarakan di Lab Komputer Utama Kampus STMIK Widya Utama Purwokerto.",
    cover_image: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?q=80&w=800&auto=format&fit=crop",
    featured: true,
  },
  {
    id: "news-2",
    slug: "juara-1-hackathon-nasional-mahasiswa-swu",
    title: "Tim Mahasiswa SWU Raih Juara 1 Hackathon IoT & AI tingkat Nasional",
    category: "Prestasi",
    is_event: false,
    author_name: "Divisi Humas",
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    event_date: null,
    reading_time: "3 min read",
    likes_count: 0,
    excerpt: "Karya inovasi Smart Campus Environment Sensor buatan mahasiswa SWU berhasil mengungguli 45 universitas lainnya pada ajang Nasional.",
    content: "Prestasi membanggakan kembali diraih oleh mahasiswa Teknik Informatika STMIK Widya Utama pada ajang National Hackathon 2026. Tim HMPSTI SWU mengusung proyek inovasi sensor lingkungan kampus pintar berbasis IoT.",
    cover_image: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=800&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "news-3",
    slug: "sosialisasi-beasiswa-prestasi-digital-2026",
    title: "Sosialisasi Beasiswa Prestasi Digital & Sertifikasi Cloud Computing 2026",
    category: "Akademik",
    is_event: false,
    author_name: "BPH Core",
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    event_date: null,
    reading_time: "5 min read",
    likes_count: 0,
    excerpt: "STMIK Widya Utama bekerjasama dengan Kemendikbud-Ristek membuka kuota 50 beasiswa sertifikasi AWS Cloud Architecture.",
    content: "HMPSTI SWU memfasilitasi sosialisasi beasiswa sertifikasi cloud computing AWS dan Google Cloud khusus untuk mahasiswa aktif prodi Teknik Informatika angkatan 2023-2025.",
    cover_image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=800&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "news-4",
    slug: "inaugurasi-dan-makrab-mahasiswa-baru-ti-2026",
    title: "Inaugurasi & Makrab Mahasiswa Baru Teknik Informatika 2026",
    category: "Event",
    is_event: true,
    author_name: "Divisi PSDM",
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    event_date: "2026-10-18T09:00:00.000Z",
    reading_time: "5 min read",
    likes_count: 0,
    excerpt: "Kegiatan tahunan keakraban anggota baru prodi Teknik Informatika untuk mempererat kebersamaan dan kaderisasi pengurus masa depan.",
    content: "Kegiatan Makrab dan Inaugurasi mahasiswa baru prodi Teknik Informatika STMIK Widya Utama akan diselenggarakan secara outdoor di Baturraden Purwokerto. Menampilkan malam inagurasi, api unggun keakraban, dan sharing session alumni.",
    cover_image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop",
    featured: true,
  },
  {
    id: "news-5",
    slug: "seminar-nasional-ai-dan-future-tech-career-2026",
    title: "Seminar Nasional Artificial Intelligence & Future Tech Career 2026",
    category: "Event",
    is_event: true,
    author_name: "Divisi Medkominfo",
    created_at: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
    event_date: "2026-11-25T08:30:00.000Z",
    reading_time: "4 min read",
    likes_count: 0,
    excerpt: "Menghadirkan praktisi senior AI dari tech unicorn nasional untuk mengupas peluang karir AI Engineering.",
    content: "Divisi Medkominfo bekerjasama dengan Asosiasi Industri Digital Purwokerto menggelar Seminar Nasional bertajuk Building Future-Ready AI Engineers. Acara terbuka untuk seluruh mahasiswa prodi TI SWU.",
    cover_image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=800&auto=format&fit=crop",
    featured: false,
  },
  {
    id: "news-6",
    slug: "bazaar-kewirausahaan-digital-dan-expo-kreatif-2026",
    title: "Bazaar Kewirausahaan Digital & Expo Produk Kreatif TI 2026",
    category: "Event",
    is_event: true,
    author_name: "Divisi KWU",
    created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    event_date: "2026-09-15T09:00:00.000Z",
    reading_time: "4 min read",
    likes_count: 0,
    excerpt: "Pameran produk startup digital dan merchandise resmi HMPSTI SWU buatan divisi Kewirausahaan.",
    content: "Divisi Kewirausahaan (KWU) HMPSTI SWU mengundang seluruh sivitas akademika kampus untuk menghadiri Expo Produk Kreatif TI 2026. Berlokasi di Aula Utama Kampus STMIK Widya Utama.",
    cover_image: "https://images.unsplash.com/photo-1531058020387-3be344556be6?q=80&w=800&auto=format&fit=crop",
    featured: false,
  },
];

export const fallbackDivisionMembers = [
  {
    id: "p-1",
    name: "Muhammad Rizky Pratama",
    role: "Ketua Umum HMPSTI",
    nim: "220101001",
    division_slug: "bph",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
    github_url: "https://github.com",
    linkedin_url: "https://linkedin.com",
    instagram_url: "https://instagram.com",
    tag: "BPH CORE",
    period: "2026",
    likes_count: 0,
  },
  {
    id: "p-2",
    name: "Fadhil Syahputra",
    role: "Wakil Ketua Umum",
    nim: "220101002",
    division_slug: "bph",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
    github_url: "https://github.com",
    linkedin_url: "https://linkedin.com",
    instagram_url: "https://instagram.com",
    tag: "BPH CORE",
    period: "2026",
    likes_count: 0,
  },
  {
    id: "p-3",
    name: "Siti Nurhaliza",
    role: "Sekretaris 1 & 2",
    nim: "220101005",
    division_slug: "bph",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop",
    github_url: "https://github.com",
    linkedin_url: "https://linkedin.com",
    instagram_url: "https://instagram.com",
    tag: "ADMINISTRASI",
    period: "2026",
    likes_count: 0,
  },
  {
    id: "p-4",
    name: "Ahmad Bagus Trio",
    role: "Bendahara 1 & 2",
    nim: "220101008",
    division_slug: "bph",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop",
    github_url: "https://github.com",
    linkedin_url: "https://linkedin.com",
    instagram_url: "https://instagram.com",
    tag: "KEUANGAN",
    period: "2026",
    likes_count: 0,
  },
  {
    id: "p-5",
    name: "Aditya Pratama",
    role: "Kepala Divisi LPT",
    nim: "220101010",
    division_slug: "lpt",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&auto=format&fit=crop",
    github_url: "https://github.com",
    linkedin_url: "https://linkedin.com",
    instagram_url: "https://instagram.com",
    tag: "DIVISI LPT",
    period: "2026",
    likes_count: 0,
  },
];

export const fallbackMembers = [
  {
    id: "m1",
    name: "Aditya Pratama",
    nim: "220101010",
    cohort: "2022",
    status: "PENGURUS AKTIF",
    role: "Kepala Divisi LPT",
    variant: "spotify",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&auto=format&fit=crop",
    instagram_url: "https://instagram.com",
    github_url: "https://github.com",
    email: "aditya@stmik-widya-utama.ac.id",
    likes_count: 0,
  },
  {
    id: "m2",
    name: "Siti Rahmawati, M.Kom.",
    nim: "0612058801",
    cohort: "2020",
    status: "DOSEN PENANGGUNG JAWAB",
    role: "Dosen Pembina HMPSTI",
    variant: "cyan",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&auto=format&fit=crop",
    instagram_url: "https://instagram.com",
    email: "siti.rahmawati@stmik-widya-utama.ac.id",
    linkedin_url: "https://linkedin.com",
    likes_count: 0,
  },
  {
    id: "m3",
    name: "Budi Santoso, S.Kom.",
    nim: "210089004",
    cohort: "2021",
    status: "ALUMNI",
    role: "Ex-Ketua Himpunan (Software Engineer)",
    variant: "yellow",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
    instagram_url: "https://instagram.com",
    github_url: "https://github.com",
    linkedin_url: "https://linkedin.com",
    likes_count: 0,
  },
  {
    id: "m4",
    name: "Dinda Permata",
    nim: "230101045",
    cohort: "2023",
    status: "PENGURUS AKTIF",
    role: "Staff Divisi PSDM",
    variant: "spotify",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
    instagram_url: "https://instagram.com",
    email: "dinda.permata@gmail.com",
    likes_count: 0,
  },
  {
    id: "m5",
    name: "Ir. Hendra Kusuma, M.T.",
    nim: "0625087502",
    cohort: "2018",
    status: "DOSEN PENANGGUNG JAWAB",
    role: "Ketua Program Studi TI",
    variant: "cyan",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=400&auto=format&fit=crop",
    email: "hendra.kusuma@stmik-widya-utama.ac.id",
    linkedin_url: "https://linkedin.com",
    likes_count: 0,
  },
  {
    id: "m6",
    name: "Rian Hidayat, S.Kom.",
    nim: "200101033",
    cohort: "2020",
    status: "ALUMNI",
    role: "Ex-Kadiv Litbang (Cloud Architect)",
    variant: "yellow",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop",
    github_url: "https://github.com",
    linkedin_url: "https://linkedin.com",
    likes_count: 0,
  },
];

export const fallbackProjects = [
  {
    id: "p1",
    slug: "swu-academic-cloud-hub",
    title: "SWU Academic Cloud Hub",
    category: "WEB APP",
    description: "Platform agregasi jadwal kuliah, absensi QR presensi, dan repositori tugas interaktif untuk mahasiswa Teknik Informatika STMIK Widya Utama.",
    content: "SWU Academic Cloud Hub adalah platform terpadu yang dirancang khusus untuk menyederhanakan manajemen perkuliahan harian mahasiswa Teknik Informatika STMIK Widya Utama. Platform ini menggabungkan sinkronisasi jadwal perkuliahan real-time, presensi digital berbasis QR Code terenkripsi, repositori materi kuliah terorganisir per semester, dan sistem pengumpulan tugas otomatis dengan notifikasi deadline perkuliahan.\n\nDikembangkan dengan arsitektur modern Next.js 15 App Router dan Supabase Postgres, sistem ini mampu menangani ribuan request secara bersamaan dengan performa responsif, antarmuka ramah pengguna, serta integrasi autentikasi SSO berbasis akun kampus.",
    author_name: "Aditya Pratama",
    author_nim: "220101010",
    author_role: "Fullstack Developer (Angkatan 2022)",
    tech_stack: ["Next.js 15", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL"],
    github_url: "https://github.com/hmpsti-swu/academic-cloud-hub",
    demo_url: "https://academic.hmpsti-swu.org",
    cover_image: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=1200&auto=format&fit=crop",
    created_at: "2026-08-15T10:00:00.000Z",
    likes_count: 0,
  },
  {
    id: "p2",
    slug: "ai-syntax-reviewer",
    title: "AI Syntax Reviewer & Code Mentor",
    category: "AI & ML",
    description: "Asisten analitik kode otomatis berbasis Large Language Model untuk membantu mahasiswa tingkat awal belajar algoritma dan pemrograman terstruktur.",
    content: "AI Syntax Reviewer & Code Mentor merupakan inovasi asisten coding cerdas yang memanfaatkan model bahasa besar (LLM) untuk membedah kode program mahasiswa. Sistem ini mampu mengidentifikasi kesalahan sintaksis, menganalisis kompleksitas algoritma Big-O, memberikan saran refaktorisasi clean code, dan menjelaskan langkah-langkah logika pemrograman secara interaktif dalam Bahasa Indonesia.\n\nProyek ini telah diuji coba pada praktikum Algoritma & Pemrograman I dan terbukti membantu mempercepat pemahaman sintaksis bahasa C++ dan Python bagi mahasiswa semester awal.",
    author_name: "Siti Rahmawati",
    author_nim: "220101004",
    author_role: "AI Engineer & Lead Researcher",
    tech_stack: ["Python", "FastAPI", "OpenAI API", "React", "Tailwind CSS"],
    github_url: "https://github.com/hmpsti-swu/ai-code-mentor",
    demo_url: "https://codementor.hmpsti-swu.org",
    cover_image: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?q=80&w=1200&auto=format&fit=crop",
    created_at: "2026-07-20T08:30:00.000Z",
    likes_count: 0,
  },
  {
    id: "p3",
    slug: "smart-campus-iot-energy",
    title: "Smart Campus IoT Energy & Environment Tracker",
    category: "IOT & EMBEDDED",
    description: "Jaringan sensor pintar IoT untuk memantau konsumsi energi listrik laboratorium komputer dan parameter kualitas udara ruangan kampus.",
    content: "Proyek Smart Campus IoT Energy & Environment Tracker dibangun menggunakan mikrokontroler ESP32 dan berbagai sensor lingkungan seperti DHT22, MQ-135, dan PZEM-004T. Perangkat ini mengirimkan telemetri data daya listrik, suhu, kelembaban, dan indeks kualitas udara (AQI) secara real-time melalui protokol MQTT ke cloud server, yang ditampilkan dalam dashboard analitik interaktif untuk efisiensi energi gedung kampus.",
    author_name: "Budi Santoso & Tim IoT",
    author_nim: "230101025",
    author_role: "Hardware & IoT Systems Specialist",
    tech_stack: ["ESP32 / C++", "MQTT", "Node.js", "Grafana", "InfluxDB"],
    github_url: "https://github.com/hmpsti-swu/smart-campus-iot",
    demo_url: "https://iot.hmpsti-swu.org",
    cover_image: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop",
    created_at: "2026-06-12T14:15:00.000Z",
    likes_count: 0,
  },
  {
    id: "p4",
    slug: "ti-connect-mobile-app",
    title: "TI-Connect: Student Community Mobile App",
    category: "MOBILE APP",
    description: "Aplikasi mobile lintas platform untuk forum diskusi akademik, direktori kelompok belajar, dan marketplace buku kuliah antar mahasiswa.",
    content: "TI-Connect menghadirkan ruang komunitas digital eksklusif mahasiswa Teknik Informatika STMIK Widya Utama di perangkat genggam. Dilengkapi fitur pembuatan room belajar bersama, forum tanya-jawab seputar coding dengan format syntax highlighting, serta fitur preloved marketplace untuk perlengkapan kuliah dan buku referensi pemrograman.",
    author_name: "Muhammad Rizky Pratama",
    author_nim: "220101001",
    author_role: "Mobile App Lead & Flutter Dev",
    tech_stack: ["Flutter", "Dart", "Firebase", "Riverpod", "REST API"],
    github_url: "https://github.com/hmpsti-swu/ti-connect-mobile",
    demo_url: "https://ticonnect.hmpsti-swu.org",
    cover_image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=1200&auto=format&fit=crop",
    created_at: "2026-05-30T16:00:00.000Z",
    likes_count: 0,
  },
  {
    id: "p5",
    slug: "algovisualizer-3d-lab",
    title: "AlgoVisualizer 3D Interactive Lab",
    category: "WEB APP",
    description: "Laboratorium visual interaktif 3D untuk memvisualisasikan algoritma pengurutan, graf, pohon biner, dan pathfinding secara spasial.",
    content: "Memahami struktur data dan algoritma kompleks sering kali menjadi tantangan bagi mahasiswa baru. AlgoVisualizer 3D Interactive Lab hadir sebagai media pembelajaran visual 3D berbasis WebGL, memungkinkan mahasiswa mengamati eksekusi algoritma seperti Dijkstra, A* Pathfinding, AVL Tree balancing, dan QuickSort secara bertahap dan 360 derajat.",
    author_name: "Fadhil Syahputra",
    author_nim: "220101002",
    author_role: "Graphics & Frontend Specialist",
    tech_stack: ["Three.js", "WebGL", "React", "TypeScript", "Tailwind CSS"],
    github_url: "https://github.com/hmpsti-swu/algovisualizer-3d",
    demo_url: "https://algo3d.hmpsti-swu.org",
    cover_image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop",
    created_at: "2026-04-18T11:20:00.000Z",
    likes_count: 0,
  },
  {
    id: "p6",
    slug: "smart-waste-sorter-cv",
    title: "Smart Waste Sorter Computer Vision",
    category: "AI & ML",
    description: "Sistem pemilah sampah otomatis berbasis Computer Vision YOLOv8 dan pemrosesan edge computing untuk kampus ramah lingkungan.",
    content: "Sebagai wujud kepedulian lingkungan kampus, tim mahasiswa TI mengembangkan Smart Waste Sorter yang memanfaatkan kamera digital dan model deteksi objek YOLOv8 pada Raspberry Pi 4. Sistem secara otomatis mengenali jenis sampah (organik, anorganik, botol plastik, kertas) dan menggerakkan aktuator pemilah ke wadah yang tepat dalam hitungan milidetik.",
    author_name: "Ahmad Bagus Trio & Tim LPT",
    author_nim: "220101008",
    author_role: "Computer Vision & Edge AI Dev",
    tech_stack: ["Python", "YOLOv8", "OpenCV", "Raspberry Pi", "TensorFlow Lite"],
    github_url: "https://github.com/hmpsti-swu/smart-waste-sorter",
    demo_url: "https://wastesorter.hmpsti-swu.org",
    cover_image: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?q=80&w=1200&auto=format&fit=crop",
    created_at: "2026-03-22T09:00:00.000Z",
    likes_count: 0,
  },
];

export const fallbackGalleryItems = [
  {
    id: "g1",
    title: "Inaugurasi & Makrab TI SWU 2026",
    category: "MAKRAB & INAUGURASI",
    event_date: "18 Oktober 2026",
    url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop",
    description: "Momen kebersamaan dan keakraban mahasiswa baru prodi Teknik Informatika STMIK Widya Utama di Baturraden.",
  },
  {
    id: "g2",
    title: "Workshop Next.js 15 & Supabase Divisi LPT",
    category: "WORKSHOP",
    event_date: "28 Agustus 2026",
    url: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?q=80&w=800&auto=format&fit=crop",
    description: "Pelatihan intensif pengembangan aplikasi web berbasis App Router dan Edge Database di Lab Komputer.",
  },
  {
    id: "g3",
    title: "Juara 1 Hackathon IoT Tingkat Nasional",
    category: "KOMPETISI",
    event_date: "12 Juli 2026",
    url: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=800&auto=format&fit=crop",
    description: "Pemberian trofi penghargaan Juara 1 Hackathon Nasional kepada tim HMPSTI STMIK Widya Utama.",
  },
];

// In-memory fallback news store to handle local edits/creates when Supabase table is offline or updating